server:
  port: 8081

spring:
  application:
    name: maji-microservice-item #指定服务名

eureka:
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中，默认为true，服务提供者
    fetchRegistry: true #是否从Eureka中获取注册信息，默认为true
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://maji:maji@127.0.0.1:6868/eureka/ #eureka开启spring-security后，需要在ip前加 user:password@
  instance:
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中


