server:
  port: 8082

microservice:
  item:
    url: http://127.0.0.1:8081/item/


spring:
  application:
    name: maji-microservice-order #指定服务名

eureka:
  client:
    registerWithEureka: false #是否将自己注册到Eureka服务中，默认为true，订单只是需要从服务端获取信息，服务消费者
    fetchRegistry: true #是否从Eureka中获取注册信息，默认为true
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://maji:maji@127.0.0.1:6868/eureka/ #eureka开启spring-security后，需要在ip前加 user:password@